controller/service_provider_controller.go, controller/state_controller.go, docker-compose.yml, main.go, middleware/cors.go, request/user.go, utility/validator.go
The following aspects have been fixed:
* Password validation bug
Validation failed because it did not consider some unicode symbols and punctuation symbols.
* Names and last name validation bug
The previous validation admited numbers. Now it does not.
=> [BR-Fixes]

controller/service_request_controller.go, mapper/service_request_mapper.go, response/service_request_response.go, route/service_provider.go, route/service_requester.go
BR-GetRequestDetails: Se añadieron dos endpoints para consultar datos generales de las requests de los serviceProvider y de los serviceRequester según una fecha específica
=> [BR-GetRequestDetails]

request/price_rate.go
fix: Había un bug en la condicional para obtener las tarifas, debido a que el mapper de los datos recibidos a la entidad no mapeaba el tipo de servicio de la tarifa a consultar
=> [BR-BigFix]

controller/address_controller.go, controller/price_rate_controller.go, controller/service_request_controller.go, controller/user_controller.go, mapper/address_mapper.go, mapper/price_rate_mapper.go, mapper/service_request_mapper.go, mapper/user_mapper.go, response/address_response.go, response/price_rate_response.go, response/service_request_response.go, response/user_response.go
[BR-FixResponseBodyPOST] Se añadieron los cuerpos de respuesta para user, request, priceRate y Address
=> [BR-FixResponseBodyPOST]

.gitignore, controller/review_controller.go, docker-compose.yml, main.go, route/service_provider.go, utility/file_analyzer.go
feat: Se añadió el endpoint para registrar imágenes o videos de evidencia para una reseña
=> [BR-UploadEvidence]

controller/price_rate_controller.go, controller/service_provider_controller.go, request/price_rate.go, route/service_provider.go
Se corrigieron errores de falta de validación y se corrigió le entidad de entrada para que guarde el precio que recibe del JSON
=> [BR-FixAddPriceRate]

database/database.go
Se añadió un seeder a la base de datos para poblarla con un Estado (Veracruz) y 7 ciudades
=> [BR-DatabaseSeeder]

entity/account.go, entity/service_request.go, request/price_rate.go, request/request.go, request/request_status.go, request/user.go
Se actualizaron los valores de los enums para empezar desde 1 y no desde 0
=> [BR-EnumsUpdate]

controller/price_rate_controller.go, route/service_provider.go
Se creo el endpoint para hacer un soft delete de la tarifa en base a su id y el id del service provider
=> [BR-DeletePriceRate]

controller/review_controller.go, controller/service_provider_controller.go, request/price_rate.go, utility/pagination.go, utility/validator.go
Se regresan los links en las paginaciones.
Se cambió para que el precio de la tarifa sea mayor que 0.
Se corrigió el regex
=> BR-FixPaginationAndInputs

controller/address_controller.go, controller/price_rate_controller.go, controller/review_controller.go, controller/service_provider_controller.go, controller/service_request_controller.go, controller/state_controller.go
Cambios de código de respuesta
=> BR-ChangeStatus

controller/address_controller.go, controller/service_request_controller.go, controller/user_controller.go, docker-compose.yml
Cambiar la forma de que cambia el estado y docker compose
=> BR-VerifyServiceRequestStatus

request/request.go, utility/validator.go
Corrección de la validación de la descripción de una solicitud de servicio
=> BR-FixServiceRequestDescription

controller/price_rate_controller.go, controller/service_request_controller.go, controller/user_controller.go, go.mod, go.sum, middleware/authentication.go, middleware/cors.go, middleware/service_provider_authorization.go, middleware/service_requester_authorization.go, route/user.go, utility/authorizer.go, utility/server_time.go
* Se corrigió bug de tarifa activa. Antes se recuperaba la tarifa activa dentro del horario pero no se tomaba en cuenta el día de la semana.
Es decir, si la tarifa sólo aplicaba en lunes pero se buscaba en martes,
aún así la tarifa se recuperaba.
* Se corrigió un bug que ocurría al intentar cambiar el estado de una solicitud
de servicio. La consulta estaba mal estructurada, lo que causaba comportamientos
inesperados. También se corrigió el código de retorno; se retornaba 200 cuando
en realidad debía retornar un 204, ya que la respuesta no incluye contenido.
* Se cambió el mecanismo de autenticación; el token ahora se envía en el cuerpo
de la respuesta al hacer login, y el refresh token se envía como una http only cookie.
También se agregaron más campos al custom claim del token; ahora se …
=> [BR-CodeMainteneance]

controller/user_controller.go, mapper/user_mapper.go, response/user_response.go
chore: Se corrigió un bug en la funcionalidad de enviar y refrescar c……ódigo de activación. El servidor retornaba un 401 debido a que no recibía un token de autenticación, ya que en la respuesta de registro no se contemplaba el envío del mismo.
Cambios:
* Se añadió un JWT token a la respuesta de registro.
* Se añadieron los campos UserID y Token a la respuesta de registro.
* Se añadió el campo UserID al mapper de la respuesta de registro.
=> [BR-BugFixActivationCode]

controller/price_rate_controller.go, controller/review_controller.go, controller/service_provider_controller.go, docker-compose.yml, entity/review.go, request/review.go
Se mejoró el código en los siguientes aspectos:
- Se regresa un json con el mensaje de error en "Generar estadísticas"
- Se corrige la validación de cityId en "Recuperar tarifas"
- Se crea una validación para que solo se pueda reseñar una solicitud una vez en "Añadir reseña"
=> BR-CodeImprovements

controller/user_controller.go
Chore: se añadió un token y refresh token a la respuesta del registro de usuario
=> [BR-TokenAndRefreshTokenOnRegistryResponse]

controller/review_controller.go
chore: Las evidencias se registraban en el sistema de archivos pero no en la base de datos; había olvidado incluir el statement, pero ya está arreglado. Ahora las evidencias también se muestran en la base de datos
=> [BR-AddEvidencesToDatabase]

controller/review_controller.go, controller/service_provider_controller.go, logs/requests.log, request/user.go
fix: Se corrigió el código para que ahora sí modifique la calificación del proveedor de servicio tras cada review
=> [BR-UpdateScore]

controller/address_controller.go, controller/price_rate_controller.go, controller/review_controller.go, controller/service_request_controller.go, controller/user_controller.go, logs/requests.log
chore: Se cambiaron algunos códigos 200 por 204 (en la actualización de código de verficiación) y códigos 200 por 201 en las acciones POST
=> [BR-ResponseStatusModification]

controller/review_controller.go, controller/service_provider_controller.go, go.mod, go.sum, request/user.go
fix: Se arreglaron los siguientes problemas:
* Se agregó un flash message para notificar un código de activación incorrecto.
* Se corrigió un error en el texto de validación de hora de fin en el registro de una tarifa
* Se cambió el mensaje de estadísticas sin datos por uno más descriptivo
* Se añadió un flash message al eliminar una tarifa
* Se sanitizaron nombres de archivos subidos
=> [BR-HotFix]
